apiVersion: batch/v1
kind: CronJob
metadata:
  name: quarterly-reports-cronjob
spec:
  schedule: "0 3 * * *" # Quarterly on the 1st at 3 AM UTC
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: quarterly-reports-container
              image: tomergahtan/quarterly-reports:1.0.0
              imagePullPolicy: Always
              env:
                - name: PSQL
                  valueFrom:
                    secretKeyRef:
                      name: my-secrets
                      key: PSQL
                - name: TZ
                  value: "Asia/Jerusalem"
              volumeMounts:
                - name: logs-volume
                  mountPath: /logs
          restartPolicy: OnFailure
          volumes:
            - name: logs-volume
              hostPath:
                path: /mnt/quaterly_reports_logs
